POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjAxODA2ODEsInVzZXJJZCI6MX0.hYjPdN0BJdToVuWwBbXHKM-JgALeay4iOJOIeY6DFw4

{
    "name": "test event",
    "description": "test event",
    "location": "test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}
