PUT http://localhost:8080/events
Content-Type: application/json
Authorization: {token}

{
    "name": "updated test event",
    "description": "updated test event",
    "location": "updated test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}
